### PR TITLE
cargo: update `openssl` and its dependency

### PR DESCRIPTION
**Pull request by tormath1**
in order to support OpenSSLv3 with `afterburn`, we need to bump the
version of `openssl`.
with this commit, it builds correctly with `dev-libs/openssl-3.0.0`

$ cargo --version
cargo 1.53.0 (4369396ce 2021-04-27)

Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>

### CODE REVIEW

**Comment by krnowak** [comment]
Hm, did you forget to include the `Cargo.toml` changes in the PR?

**Comment by pothos** [comment]
I also had to look up the dependency versioning syntax, it has `^major.minor.patch` which means that the latest patch version is taken if present. So no update of the file needed.

**Comment by krnowak** [comment]
> I also had to look up the dependency versioning syntax, it has `^major.minor.patch` which means that the latest patch version is taken if present. So no update of the file needed.

Ah, alright. Thanks. :)

This PR obviously isn't very reviewable, but I had a look at https://docs.rs/openssl/0.10.36/openssl/ and it says that the compatibility is with openssl from 1.0.1 to 1.1.1. But if it builds then I suppose that it's fine.

**Review by krnowak — APPROVED** [review]

**Comment by tormath1** [comment]
@krnowak that's right, compatibility is suppose to stay across the various versions of OpenSSL. There is this test matrix on the rust-openssl repository: https://github.com/sfackler/rust-openssl/blob/bf20ebeb3e023eba142da0329825202b1713c0cf/.github/workflows/ci.yml#L148-L164

CI is currently running for `afterburn` with both OpenSSL version:
* openssl v3: https://github.com/flatcar-linux/coreos-overlay/pull/1305
* openssl < v3: https://github.com/flatcar-linux/coreos-overlay/pull/1315

If both are OK, I'll merge this PR.

**Comment by krnowak** [comment]
Sounds good.

**Comment by tormath1** [comment]
@pothos @krnowak CI is :large_blue_circle: for OpenSSL v3 and < v3.

**Comment by krnowak** [comment]
Please merge then. :)

**Pull request merged**
